// AUTO-GENERATED by scripts/sync-data.ts - do not edit by hand.
// Source of truth: scripts/shell-registry.sh + egg-shell-multi.json

export type Shell = {
  id: string;
  name: string;
  category: string;
  defaultPort: number;
  needsRoot: boolean;
  description: string;
};

export const SHELLS: Shell[] = [
  {
    "id": "ssh",
    "name": "OpenSSH Server",
    "category": "server",
    "defaultPort": 22,
    "needsRoot": true,
    "description": "Hardened sshd: keys, passwords, SFTP, ciphers tuned"
  },
  {
    "id": "ssh-cert",
    "name": "OpenSSH CA Certificates",
    "category": "server",
    "defaultPort": 22,
    "needsRoot": true,
    "description": "SSH user + host certificates signed by a container-local CA"
  },
  {
    "id": "ssh-hardened",
    "name": "OpenSSH Hardened",
    "category": "server",
    "defaultPort": 22,
    "needsRoot": true,
    "description": "Keys-only, strong ciphers, no root login, blinding + rate limit"
  },
  {
    "id": "dropbear",
    "name": "Dropbear SSH",
    "category": "server",
    "defaultPort": 22,
    "needsRoot": true,
    "description": "Tiny SSH for low-RAM containers (ECC + RSA keys)"
  },
  {
    "id": "telnetd",
    "name": "Telnet Server",
    "category": "server",
    "defaultPort": 23,
    "needsRoot": true,
    "description": "Classic plaintext remote terminal (RFC854) - lab use"
  },
  {
    "id": "mosh-server",
    "name": "Mosh Server",
    "category": "server",
    "defaultPort": 60000,
    "needsRoot": false,
    "description": "Roaming low-latency shell over UDP (survives IP changes)"
  },
  {
    "id": "tmux",
    "name": "Tmux Session",
    "category": "multiplexer",
    "defaultPort": 0,
    "needsRoot": false,
    "description": "Persistent terminal multiplexer, attach/detach anywhere"
  },
  {
    "id": "screen",
    "name": "GNU Screen",
    "category": "multiplexer",
    "defaultPort": 0,
    "needsRoot": false,
    "description": "Classic session multiplexer with hardstatus bar"
  },
  {
    "id": "zellij",
    "name": "Zellij Session",
    "category": "multiplexer",
    "defaultPort": 0,
    "needsRoot": false,
    "description": "Modern multiplexer with layouts, panes and session resurrection"
  },
  {
    "id": "ssh-local",
    "name": "SSH Local Tunnel (-L)",
    "category": "tunnel",
    "defaultPort": 2222,
    "needsRoot": false,
    "description": "Forward a local port through this container (encrypted pipe)"
  },
  {
    "id": "ssh-remote",
    "name": "SSH Remote Tunnel (-R)",
    "category": "tunnel",
    "defaultPort": 2222,
    "needsRoot": false,
    "description": "Expose this container's port on YOUR machine via sshd gatewaying"
  },
  {
    "id": "ssh-dynamic",
    "name": "SSH SOCKS Proxy (-D)",
    "category": "tunnel",
    "defaultPort": 2222,
    "needsRoot": false,
    "description": "SOCKS5 proxy through the container - route any app through it"
  },
  {
    "id": "ssh-x11",
    "name": "SSH X11 Forwarding",
    "category": "tunnel",
    "defaultPort": 2222,
    "needsRoot": false,
    "description": "Run remote GUI apps from the container on your X display"
  },
  {
    "id": "rsync-ssh",
    "name": "Rsync over SSH",
    "category": "tunnel",
    "defaultPort": 22,
    "needsRoot": false,
    "description": "Fast delta file sync over the encrypted SSH channel"
  },
  {
    "id": "sshfs",
    "name": "SSHFS Filesystem",
    "category": "tunnel",
    "defaultPort": 22,
    "needsRoot": false,
    "description": "Mount the container workspace as a local folder via SFTP"
  },
  {
    "id": "bash-tcp",
    "name": "Bash /dev/tcp Reverse",
    "category": "reverse",
    "defaultPort": 4444,
    "needsRoot": false,
    "description": "Pure bash reverse shell - zero external dependencies"
  },
  {
    "id": "bash-udp",
    "name": "Bash /dev/udp Reverse",
    "category": "reverse",
    "defaultPort": 4444,
    "needsRoot": false,
    "description": "UDP flavor of the bash device reverse shell"
  },
  {
    "id": "python",
    "name": "Python Reverse Shell",
    "category": "reverse",
    "defaultPort": 4444,
    "needsRoot": false,
    "description": "socket() + subprocess reverse shell (stable, reconnects)"
  },
  {
    "id": "python-pty",
    "name": "Python PTY Reverse",
    "category": "reverse",
    "defaultPort": 4444,
    "needsRoot": false,
    "description": "Python reverse shell with full PTY (arrow keys, ctrl-c)"
  },
  {
    "id": "php",
    "name": "PHP fsockopen Reverse",
    "category": "reverse",
    "defaultPort": 4444,
    "needsRoot": false,
    "description": "PHP proc_open reverse shell from any PHP runtime"
  },
  {
    "id": "php-pentest",
    "name": "PHP Pentestmonkey-style",
    "category": "reverse",
    "defaultPort": 4444,
    "needsRoot": false,
    "description": "Classic full-featured PHP reverse shell script"
  },
  {
    "id": "perl",
    "name": "Perl Socket Reverse",
    "category": "reverse",
    "defaultPort": 4444,
    "needsRoot": false,
    "description": "Core perl Socket module reverse shell"
  },
  {
    "id": "ruby",
    "name": "Ruby TCPSocket Reverse",
    "category": "reverse",
    "defaultPort": 4444,
    "needsRoot": false,
    "description": "Ruby TCPSocket + system() reverse shell"
  },
  {
    "id": "lua",
    "name": "Lua Socket Reverse",
    "category": "reverse",
    "defaultPort": 4444,
    "needsRoot": false,
    "description": "Lua io.popen loop reverse shell"
  },
  {
    "id": "node",
    "name": "Node.js net.Reverse",
    "category": "reverse",
    "defaultPort": 4444,
    "needsRoot": false,
    "description": "Node.js child_process reverse shell"
  },
  {
    "id": "powershell",
    "name": "PowerShell TCP Reverse",
    "category": "reverse",
    "defaultPort": 4444,
    "needsRoot": false,
    "description": ".NET TCPClient reverse shell for pwsh runtimes"
  },
  {
    "id": "golang",
    "name": "Golang Reverse Shell",
    "category": "reverse",
    "defaultPort": 4444,
    "needsRoot": false,
    "description": "Go source, compiled on the fly into a static binary"
  },
  {
    "id": "groovy",
    "name": "Groovy Reverse Shell",
    "category": "reverse",
    "defaultPort": 4444,
    "needsRoot": false,
    "description": "Groovy/Jenkins console reverse shell"
  },
  {
    "id": "java",
    "name": "Java Reverse Shell",
    "category": "reverse",
    "defaultPort": 4444,
    "needsRoot": false,
    "description": "Plain Java socket reverse shell, compiled at boot"
  },
  {
    "id": "awk",
    "name": "Gawk Reverse Shell",
    "category": "reverse",
    "defaultPort": 4444,
    "needsRoot": false,
    "description": "/inet/tcp gawk one-file reverse shell (surprising but real)"
  },
  {
    "id": "nc",
    "name": "Netcat Reverse",
    "category": "reverse",
    "defaultPort": 4444,
    "needsRoot": false,
    "description": "Classic TCP reverse via FIFO relay (openbsd + traditional)"
  },
  {
    "id": "nc-udp",
    "name": "Netcat UDP Reverse",
    "category": "reverse",
    "defaultPort": 4444,
    "needsRoot": false,
    "description": "UDP reverse shell (listener must speak first)"
  },
  {
    "id": "ncat",
    "name": "Ncat Reverse",
    "category": "reverse",
    "defaultPort": 4444,
    "needsRoot": false,
    "description": "Nmap's netcat with --exec and reconnect"
  },
  {
    "id": "socat",
    "name": "Socat Reverse (pty)",
    "category": "reverse",
    "defaultPort": 4444,
    "needsRoot": false,
    "description": "Fully interactive socat EXEC pty reverse shell"
  },
  {
    "id": "cryptcat",
    "name": "Cryptcat Reverse",
    "category": "reverse",
    "defaultPort": 4444,
    "needsRoot": false,
    "description": "Netcat with twofish encryption (-k shared key)"
  },
  {
    "id": "openssl-rs",
    "name": "OpenSSL TLS Reverse",
    "category": "reverse",
    "defaultPort": 4444,
    "needsRoot": false,
    "description": "TLS-wrapped shell via s_client; pairs with socat OPENSSL-LISTEN"
  },
  {
    "id": "socat-tls",
    "name": "Socat TLS Reverse",
    "category": "reverse",
    "defaultPort": 4444,
    "needsRoot": false,
    "description": "socat OPENSSL reverse shell with auto-generated client cert"
  },
  {
    "id": "ncat-ssl",
    "name": "Ncat SSL Reverse",
    "category": "reverse",
    "defaultPort": 4444,
    "needsRoot": false,
    "description": "ncat --ssl reverse shell (nmap TLS stack)"
  },
  {
    "id": "wssh",
    "name": "Websocket Shell (wssh)",
    "category": "secure-web",
    "defaultPort": 7681,
    "needsRoot": false,
    "description": "Python websocket shell client over ws:// (covert, 80/443-like)"
  },
  {
    "id": "dnscat",
    "name": "DNS Tunnel Shell",
    "category": "secure-web",
    "defaultPort": 0,
    "needsRoot": false,
    "description": "C2-over-DNS client (dnscat2-style) for egress-restricted nets"
  },
  {
    "id": "icmp-shell",
    "name": "ICMP Shell",
    "category": "secure-web",
    "defaultPort": 0,
    "needsRoot": false,
    "description": "Reverse shell inside ICMP echo payloads (icmpsh-style)"
  },
  {
    "id": "nc-bind",
    "name": "Netcat Bind Shell",
    "category": "bind",
    "defaultPort": 5555,
    "needsRoot": false,
    "description": "nc -lp /bin/sh - classic bind shell on demand"
  },
  {
    "id": "socat-bind",
    "name": "Socat Bind Shell (pty)",
    "category": "bind",
    "defaultPort": 5555,
    "needsRoot": false,
    "description": "Full PTY bind shell via socat TCP-LISTEN"
  },
  {
    "id": "openssl-bind",
    "name": "OpenSSL TLS Bind",
    "category": "bind",
    "defaultPort": 5555,
    "needsRoot": false,
    "description": "TLS bind shell: socat OPENSSL-LISTEN + bash"
  },
  {
    "id": "php-bind",
    "name": "PHP Bind Shell",
    "category": "bind",
    "defaultPort": 5555,
    "needsRoot": false,
    "description": "PHP socket_accept bind shell"
  },
  {
    "id": "python-bind",
    "name": "Python Bind Shell",
    "category": "bind",
    "defaultPort": 5555,
    "needsRoot": false,
    "description": "Python socket bind + PTY shell"
  },
  {
    "id": "ttyd",
    "name": "ttyd Web Terminal",
    "category": "web",
    "defaultPort": 7681,
    "needsRoot": false,
    "description": "Full xterm.js terminal in your browser (TLS optional)"
  },
  {
    "id": "gotty",
    "name": "GoTTY Web Terminal",
    "category": "web",
    "defaultPort": 8080,
    "needsRoot": false,
    "description": "Go static binary web terminal - no install on client"
  },
  {
    "id": "php-webshell",
    "name": "PHP Web Shell (HTTP)",
    "category": "web",
    "defaultPort": 8080,
    "needsRoot": false,
    "description": "POST cmd= PHP HTTP exec shell served by php -S"
  },
  {
    "id": "node-webshell",
    "name": "Node.js Web Shell",
    "category": "web",
    "defaultPort": 8080,
    "needsRoot": false,
    "description": "Node http server exec shell - cmd= query or POST body"
  },
  {
    "id": "ssh-debug",
    "name": "SSH Debug Session",
    "category": "debug",
    "defaultPort": 2222,
    "needsRoot": false,
    "description": "Foreground sshd -ddd + client -vvv recipe for auth issues"
  },
  {
    "id": "strace-shell",
    "name": "Strace Session Shell",
    "category": "debug",
    "defaultPort": 0,
    "needsRoot": false,
    "description": "Login shell wrapper that straces every syscall to file"
  },
  {
    "id": "tcpdump-shell",
    "name": "Tcpdump Capture Shell",
    "category": "debug",
    "defaultPort": 0,
    "needsRoot": false,
    "description": "Bind a shell that also captures traffic to pcap for review"
  },
  {
    "id": "socat-probe",
    "name": "Socat Probe Relay",
    "category": "debug",
    "defaultPort": 9000,
    "needsRoot": false,
    "description": "Raw TCP relay + hex dump for protocol debugging"
  }
];

export const CATEGORY_META: Record<string, { label: string; blurb: string; accent: string }> = {
  "server": {
    "label": "Server Shells",
    "blurb": "SSH (standard, CA-certified, hardened), Dropbear, Telnet and Mosh listeners",
    "accent": "#22d3ee"
  },
  "multiplexer": {
    "label": "Multiplexers",
    "blurb": "tmux, screen and zellij persistent sessions",
    "accent": "#a78bfa"
  },
  "tunnel": {
    "label": "Tunnels",
    "blurb": "SSH -L / -R / -D forwarding, X11, rsync and sshfs",
    "accent": "#34d399"
  },
  "reverse": {
    "label": "Reverse Shells",
    "blurb": "Interpreter and netcat-family callbacks, plain TCP/UDP",
    "accent": "#fb923c"
  },
  "secure-web": {
    "label": "Secure / Covert",
    "blurb": "TLS-wrapped shells plus websocket, DNS and ICMP channels",
    "accent": "#f472b6"
  },
  "bind": {
    "label": "Bind Shells",
    "blurb": "Listeners inside the container, plain and TLS",
    "accent": "#facc15"
  },
  "web": {
    "label": "Web Terminals",
    "blurb": "Browser xterm.js terminals and token-authed HTTP shells",
    "accent": "#60a5fa"
  },
  "debug": {
    "label": "Debug Shells",
    "blurb": "sshd -ddd, strace, tcpdump and socat probe harnesses",
    "accent": "#94a3b8"
  }
};

export const CATEGORY_COUNTS: Record<string, number> = {
  "server": 6,
  "multiplexer": 3,
  "tunnel": 6,
  "reverse": 23,
  "secure-web": 3,
  "bind": 5,
  "web": 4,
  "debug": 4
};

export const EGG_VARIABLES = [
  {
    "env": "SHELL_TYPE",
    "name": "Shell Type",
    "description": "Which shell(s) to run. 'auto' opens an interactive paginated picker in the console on first boot. Otherwise a comma-separated list of ids:",
    "defaultValue": "auto",
    "mandatory": false
  },
  {
    "env": "SHELL_USERS",
    "name": "Shell Usernames",
    "description": "MANDATORY in practice: comma-separated login users created inside the container (e.g. 'alice,bob'). Each gets a private home + bash. Invalid names are skipped with a warning.",
    "defaultValue": "",
    "mandatory": true
  },
  {
    "env": "SHELL_PASSWORDS",
    "name": "Shell User Passwords",
    "description": "Positionally matched to Shell Usernames ('S3cretA,S3cretB'). Empty or 'auto' slots generate cryptographically random secrets (recorded in .env and .sh-users/credentials, mode 600, shown once in console).",
    "defaultValue": "auto",
    "mandatory": false
  },
  {
    "env": "SHELL_EXTRA_TYPES",
    "name": "Extra Shell Types",
    "description": "OPTIONAL: additional shell ids to run alongside the primary (same catalog as Shell Type). Example: 'socat,tmux' to also run a socat reverse shell and a tmux session.",
    "defaultValue": "",
    "mandatory": false
  },
  {
    "env": "SHELL_EXTRA_PORTS",
    "name": "Extra Ports",
    "description": "OPTIONAL: comma-separated extra panel ports for additional PORTED shells (the primary shell always binds this server's default port). Positionally matched to Extra Shell Types order. Reverse shells and multiplexers need no port.",
    "defaultValue": "",
    "mandatory": false
  },
  {
    "env": "SHELL_REVERSE_HOST",
    "name": "Reverse Target Host",
    "description": "OPTIONAL: where reverse shells connect OUT to (your public IP / listener host). Required only when running reverse shells.",
    "defaultValue": "",
    "mandatory": false
  },
  {
    "env": "SHELL_REVERSE_PORT",
    "name": "Reverse Target Port",
    "description": "OPTIONAL: port of your listener (nc -lvnp). Default 4444.",
    "defaultValue": "4444",
    "mandatory": false
  },
  {
    "env": "SHELL_REVERSE_TLS",
    "name": "TLS Reverse Shells",
    "description": "OPTIONAL: 1 = TLS-capable reverse profiles (ncat, socat) wrap the channel with TLS when both sides support it.",
    "defaultValue": "0",
    "mandatory": false
  },
  {
    "env": "SHELL_SSH_PUBKEY_RAW",
    "name": "SSH Public Key",
    "description": "OPTIONAL: your public key (one line, e.g. ssh-ed25519 AAAA... comment). Installed into authorized_keys; the ONLY way in for the ssh-hardened profile.",
    "defaultValue": "",
    "mandatory": false
  },
  {
    "env": "SHELL_SSH_PASSWORD_AUTH",
    "name": "SSH Password Auth",
    "description": "OPTIONAL: yes/no for the standard ssh + ssh-cert profiles (ssh-hardened is always keys-only).",
    "defaultValue": "yes",
    "mandatory": false
  },
  {
    "env": "SHELL_MOSH_UDP_START",
    "name": "MOSH UDP Start Port",
    "description": "OPTIONAL: first UDP port for Mosh roaming (opens SHELL_MOSH_UDP_COUNT ports downward range). Default 60000.",
    "defaultValue": "60000",
    "mandatory": false
  },
  {
    "env": "SHELL_WEB_USER",
    "name": "Web Shell User",
    "description": "OPTIONAL: basic-auth user for ttyd/gotty web terminals (password below). Empty = first generated credential is used.",
    "defaultValue": "",
    "mandatory": false
  },
  {
    "env": "SHELL_WEB_PASS",
    "name": "Web Shell Password",
    "description": "OPTIONAL: basic-auth password for ttyd/gotty.",
    "defaultValue": "",
    "mandatory": false
  },
  {
    "env": "SHELL_WEB_TOKEN",
    "name": "Web Shell Token",
    "description": "OPTIONAL: bearer token for php/node web shells (auto-generated when empty, shown once in console).",
    "defaultValue": "",
    "mandatory": false
  },
  {
    "env": "SHELL_MOTD",
    "name": "MOTD Banner",
    "description": "OPTIONAL: message shown on every shell login.",
    "defaultValue": "Welcome to the Multi-Shell Universal Egg (PotenFYR Studios).",
    "mandatory": false
  },
  {
    "env": "SHELL_MUX_SESSION",
    "name": "Multiplexer Session Name",
    "description": "OPTIONAL: tmux/screen session name. Default 'shell-eggs'.",
    "defaultValue": "shell-eggs",
    "mandatory": false
  },
  {
    "env": "DEFAULT_SHELL_MUX",
    "name": "Default Login Multiplexer",
    "description": "OPTIONAL: tmux|screen - drop SSH/Telnet logins straight into the persistent session.",
    "defaultValue": "",
    "mandatory": false
  },
  {
    "env": "SHELL_SHOW_CREDENTIALS",
    "name": "Show Credentials in Console",
    "description": "OPTIONAL: 1 = print generated credentials on the boot console (they are always written to .env and .sh-users/credentials, mode 600).",
    "defaultValue": "1",
    "mandatory": false
  },
  {
    "env": "AUTO_GENERATE_CREDENTIALS",
    "name": "Auto Generate Credentials",
    "description": "1 = generate crypto-random secrets for empty/'auto' password slots and persist them. Credentials are the one mandatory input of this egg - everything else is optional.",
    "defaultValue": "1",
    "mandatory": false
  },
  {
    "env": "PANEL_STOP_WATCHER",
    "name": "Panel Stop Watcher",
    "description": "Watch console stdin for stop commands ('stop', '^C', 'exit', ...) delivered as text by TTY daemons. auto = on for all consoles; 0 = disable; 1 = force on.",
    "defaultValue": "auto",
    "mandatory": false
  },
  {
    "env": "CLI_THEME",
    "name": "Console Theme",
    "description": "Console output style. 'sh' = agent theme (</> shell-eggs prefixes); 'classic' = [PotenFYR] bracket style.",
    "defaultValue": "sh",
    "mandatory": false
  },
  {
    "env": "CLI_BANNER_GRADIENT",
    "name": "Banner Gradient",
    "description": "Boot banner gradient: auto (random per boot), aurora, candy, citrus, forest, sunset, ocean, or none.",
    "defaultValue": "auto",
    "mandatory": false
  },
  {
    "env": "EGG_UPDATE_URL",
    "name": "Egg Update URL",
    "description": "Check on startup and self-update the launcher when the upstream egg changed (raw GitHub egg JSON or entrypoint URL).",
    "defaultValue": "https://raw.githubusercontent.com/PotenFYR-Studios/Shell-Eggs/main/egg-shell-multi.json",
    "mandatory": false
  },
  {
    "env": "AUTO_UPDATE_EGG",
    "name": "Auto Update Egg",
    "description": "1 = check EGG_UPDATE_URL on startup and self-update. 0 = disable the check entirely.",
    "defaultValue": "1",
    "mandatory": false
  }
];

export const TOTAL_SHELLS = 54;
