#!/usr/bin/env bun
/**
 * docs/scripts/sync-data.ts
 * Syncs the live shell catalog + egg variables from the repo root into
 * typed data modules, so the website always matches SHELLs.md and the egg JSON.
 * Runs on every Pages build (auto-sync).
 */
import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";

const root = resolve(import.meta.dir, "../..");

// ---------------------------------------------------------------- catalog
const registry = readFileSync(resolve(root, "scripts/shell-registry.sh"), "utf8");
const re = /register_shell\s+(\S+)\s+"([^"]+)"\s+(\S+)\s+(\S+)\s+(\S+)\s+"([^"]+)"/g;

type Shell = {
  id: string;
  name: string;
  category: string;
  defaultPort: number;
  needsRoot: boolean;
  description: string;
};

const shells: Shell[] = [];
let m: RegExpExecArray | null;
while ((m = re.exec(registry)) !== null) {
  shells.push({
    id: m[1],
    name: m[2],
    category: m[3],
    defaultPort: Number(m[4]),
    needsRoot: m[5] === "1",
    description: m[6],
  });
}

const CATEGORY_META: Record<string, { label: string; blurb: string; accent: string }> = {
  server: { label: "Server Shells", blurb: "SSH (standard, CA-certified, hardened), Dropbear, Telnet and Mosh listeners", accent: "#22d3ee" },
  multiplexer: { label: "Multiplexers", blurb: "tmux, screen and zellij persistent sessions", accent: "#a78bfa" },
  tunnel: { label: "Tunnels", blurb: "SSH -L / -R / -D forwarding, X11, rsync and sshfs", accent: "#34d399" },
  reverse: { label: "Reverse Shells", blurb: "Interpreter and netcat-family callbacks, plain TCP/UDP", accent: "#fb923c" },
  "secure-web": { label: "Secure / Covert", blurb: "TLS-wrapped shells plus websocket, DNS and ICMP channels", accent: "#f472b6" },
  bind: { label: "Bind Shells", blurb: "Listeners inside the container, plain and TLS", accent: "#facc15" },
  web: { label: "Web Terminals", blurb: "Browser xterm.js terminals and token-authed HTTP shells", accent: "#60a5fa" },
  debug: { label: "Debug Shells", blurb: "sshd -ddd, strace, tcpdump and socat probe harnesses", accent: "#94a3b8" },
};

// ---------------------------------------------------------------- egg variables
const egg = JSON.parse(readFileSync(resolve(root, "egg-shell-multi.json"), "utf8"));
const variables = (egg.variables ?? []).map((v: any) => ({
  env: v.env_variable,
  name: v.name,
  description: v.description.split("\n")[0],
  defaultValue: v.default_value,
  mandatory: v.env_variable === "SHELL_USERS",
}));

// ---------------------------------------------------------------- counts
const counts: Record<string, number> = {};
for (const s of shells) counts[s.category] = (counts[s.category] ?? 0) + 1;

const out = `// AUTO-GENERATED by scripts/sync-data.ts - do not edit by hand.
// Source of truth: scripts/shell-registry.sh + egg-shell-multi.json

export type Shell = {
  id: string;
  name: string;
  category: string;
  defaultPort: number;
  needsRoot: boolean;
  description: string;
};

export const SHELLS: Shell[] = ${JSON.stringify(shells, null, 2)};

export const CATEGORY_META: Record<string, { label: string; blurb: string; accent: string }> = ${JSON.stringify(CATEGORY_META, null, 2)};

export const CATEGORY_COUNTS: Record<string, number> = ${JSON.stringify(counts, null, 2)};

export const EGG_VARIABLES = ${JSON.stringify(variables, null, 2)};

export const TOTAL_SHELLS = ${shells.length};
`;

writeFileSync(resolve(import.meta.dir, "../src/data/catalog.ts"), out);
console.log(`synced ${shells.length} shells, ${variables.length} egg variables`);
