#!/usr/bin/env bash
# ============================================================================
#  PotenFYR Studios - Multi-Shell Universal Egg :: scripts/shell-init-server.sh
#  Handlers for incoming shells: init_ssh, init_dropbear, init_telnetd,
#  init_mosh. Each returns 0 when the service is running (or handed to the
#  supervisor); they must never block longer than the boot budget.
# ============================================================================
# shellcheck source=shell-core.sh
[ -n "${SHELL_CORE_LOADED:-}" ] || source "${SCRIPTS_DIR}/shell-core.sh"

# ---------------------------------------------------------------- users
# Ensure OS accounts exist for the plan users. In panels we are root inside
# the container, so this is safe; standalone runs as non-root degrade to
# sshd's internal-user mode (Dropbear) or a passwordless demo notice.
ensure_os_users() {
    local i u p
    for i in "${!SHELL_PLAN_USERS[@]}"; do
        u="${SHELL_PLAN_USERS[${i}]}"
        p="${SHELL_PLAN_PASSWORDS[${i}]:-}"
        if id "${u}" >/dev/null 2>&1; then
            if [ -n "${p}" ] && is_root; then
                printf '%s:%s\n' "${u}" "${p}" | chpasswd 2>/dev/null || true
            fi
            continue
        fi
        if ! is_root; then
            warn "Cannot create OS user '${u}' without root; only SSH keys/in-app auth will work."
            continue
        fi
        useradd -m -s /bin/bash "${u}" 2>/dev/null || {
            warn "useradd failed for '${u}'; skipping"
            continue
        }
        if [ -n "${p}" ]; then
            # SHA-512: verifiable by stdlib crypt AND the openssl fallback in
            # scripts/telnetd.py (python3.13+ removed the crypt module).
            printf '%s:%s\n' "${u}" "${p}" | chpasswd -c SHA512 2>/dev/null \
                || printf '%s:%s\n' "${u}" "${p}" | chpasswd 2>/dev/null || true
        fi
        ok "OS user ready: ${u}"
    done
}

ssh_ready_wait() { # wait until sshd answers on its port (max ~10s)
    local port="$1" i
    for i in $(seq 1 20); do
        if have nc && nc -z 127.0.0.1 "${port}" >/dev/null 2>&1; then return 0; fi
        sleep 0.5
    done
    return 1
}

# ---------------------------------------------------------------- OpenSSH
init_ssh() {
    ssh_server_dir="${SERVER_DIR}/.ssh-host"
    mkdir -p "${ssh_server_dir}" "${SERVER_DIR}/.ssh-pub" /run/sshd 2>/dev/null || true
    chmod 0755 /run/sshd 2>/dev/null || true

    pkg_install openssh-server openssh-sftp-server || true
    have sshd || { fail "sshd not available and could not be installed"; return 1; }

    ensure_os_users

    # Host keys: persistent under the server dir so restarts keep identity.
    if [ ! -f "${ssh_server_dir}/ssh_host_ed25519_key" ]; then
        log "Generating SSH host keys..."
        ssh-keygen -A >/dev/null 2>&1 || true
        for kt in rsa ecdsa ed25519; do
            kf="/etc/ssh/ssh_host_${kt}_key"
            [ -f "${kf}" ] && cp -f "${kf}" "${ssh_server_dir}/" 2>/dev/null
        done
    fi
    for kt in rsa ecdsa ed25519; do
        kf="${ssh_server_dir}/ssh_host_${kt}_key"
        [ -f "${kf}" ] || ssh-keygen -q -t "${kt}" -N '' -f "${kf}" >/dev/null 2>&1 || true
    done

    local port
    port=$(allocate_port "ssh" "${SHELL_BIND_PORT:-${SSH_PORT:-22}}")

    local auth_keys_mode=0
    if [ -n "${SHELL_SSH_PUBKEY_RAW:-}" ]; then
        printf '%s\n' "${SHELL_SSH_PUBKEY_RAW}" > "${SERVER_DIR}/.ssh-pub/authorized_keys"
        chmod 600 "${SERVER_DIR}/.ssh-pub/authorized_keys"
        auth_keys_mode=1
    fi

    write_motd_file /etc/motd 2>/dev/null || true

    cat > "${ssh_server_dir}/sshd_config" << EOF
# generated by shell-eggs
Port ${port}
ListenAddress 0.0.0.0
HostKey ${ssh_server_dir}/ssh_host_rsa_key
HostKey ${ssh_server_dir}/ssh_host_ecdsa_key
HostKey ${ssh_server_dir}/ssh_host_ed25519_key
PermitRootLogin ${SHELL_SSH_ROOT_LOGIN:-prohibit-password}
PasswordAuthentication ${SHELL_SSH_PASSWORD_AUTH:-yes}
KbdInteractiveAuthentication yes
ChallengeResponseAuthentication no
UsePAM ${SHELL_SSH_USE_PAM:-no}
PubkeyAuthentication yes
AuthorizedKeysFile ${SERVER_DIR}/.ssh-pub/authorized_keys .ssh/authorized_keys
AllowTcpForwarding yes
X11Forwarding no
PrintMotd yes
AcceptEnv LANG LC_*
Subsystem sftp internal-sftp
EOF
    # PAM is absent in most egg images; only enable when present.
    if [ -f /etc/pam.d/sshd ] && [ "${SHELL_SSH_USE_PAM:-no}" = "yes" ]; then :; fi

    log "Starting sshd on port ${port}..."
    /usr/sbin/sshd -f "${ssh_server_dir}/sshd_config" -E "${SERVER_DIR}/logs/sshd.log" || {
        fail "sshd failed to start (see logs/sshd.log)"
        return 1
    }
    ssh_ready_wait "${port}" && ok "SSH ready on port ${port}" || warn "SSH port not answering yet (continuing)"
    SHELL_DESC_EXTRA["ssh"]="
CONNECT (from your machine):
  ssh -p ${port} <user>@<this-host>          # password or key login
  sftp -P ${port} <user>@<this-host>         # file transfer over the same auth
KEY COMPONENTS:
  port ${port}    the panel-assigned container port (SHELL_BIND_PORT)
  <user>          one of: ${SHELL_PLAN_USERS[*]:-root-user}
  first time?     accept the host key fingerprint or pin it:
                  ssh-keyscan -p ${port} <host> >> ~/.ssh/known_hosts"
    return 0
}

# ---------------------------------------------------------------- CA certificates
init_ssh_cert() {
    local port="${SHELL_BIND_PORT:-22}"
    local ca_dir="${SERVER_DIR}/.ssh-ca"
    mkdir -p "${ca_dir}" "${SERVER_DIR}/.ssh-host" /run/sshd 2>/dev/null || true

    pkg_install openssh-server openssh-client || true
    have sshd || { fail "sshd unavailable"; return 1; }
    ensure_os_users

    # --- container-local certificate authority --------------------------- #
    if [ ! -f "${ca_dir}/ca_user_key" ]; then
        log "Generating SSH certificate authority (user + host CA)..."
        ssh-keygen -q -t ed25519 -N '' -f "${ca_dir}/ca_user_key" -C "shell-eggs-user-CA" >/dev/null 2>&1
        ssh-keygen -q -t ed25519 -N '' -f "${ca_dir}/ca_host_key" -C "shell-eggs-host-CA" >/dev/null 2>&1
    fi

    # host keys + host certificate
    for kt in rsa ecdsa ed25519; do
        kf="${SERVER_DIR}/.ssh-host/ssh_host_${kt}_key"
        [ -f "${kf}" ] || ssh-keygen -q -t "${kt}" -N '' -f "${kf}" >/dev/null 2>&1 || true
    done
    local hostname
    hostname=$(hostname -f 2>/dev/null || hostname || echo shell-eggs-host)
    if [ ! -f "${SERVER_DIR}/.ssh-host/ssh_host_ed25519_key-cert.pub" ]; then
        ssh-keygen -q -s "${ca_dir}/ca_host_key" -I "shell-eggs-host" -h -n "${hostname},shell-eggs,localhost" \
            -V -5m:+520w "${SERVER_DIR}/.ssh-host/ssh_host_ed25519_key.pub" >/dev/null 2>&1 || true
    fi

    # per-user certificates signed by the user CA (for every plan user)
    local i u
    for i in "${!SHELL_PLAN_USERS[@]}"; do
        u="${SHELL_PLAN_USERS[${i}]}"
        id "${u}" >/dev/null 2>&1 || continue
        local uh="${SERVER_DIR}/.ssh-ca/${u}"
        if [ ! -f "${uh}-cert.pub" ]; then
            [ -f "${uh}" ] || ssh-keygen -q -t ed25519 -N '' -f "${uh}" -C "${u}@shell-eggs" >/dev/null 2>&1
            ssh-keygen -q -s "${ca_dir}/ca_user_key" -I "${u}-cert" -n "${u}" \
                -V -5m:+52w "${uh}.pub" >/dev/null 2>&1 || true
            # install cert+key into the user's home too (client-side copy)
            local home_dir
            home_dir=$(eval echo "~${u}" 2>/dev/null || echo "/home/${u}")
            [ -d "${home_dir}" ] && {
                mkdir -p "${home_dir}/.ssh" 2>/dev/null || true
                cp -f "${uh}" "${uh}-cert.pub" "${home_dir}/.ssh/" 2>/dev/null || true
                chown -R "${u}:${u}" "${home_dir}/.ssh" 2>/dev/null || true
            }
        fi
    done

    # sshd trusts ONLY the CA (passwords still allowed unless hardened profile)
    cat > "${SERVER_DIR}/.ssh-host/sshd_cert_config" << EOF
Port ${port}
ListenAddress 0.0.0.0
HostKey ${SERVER_DIR}/.ssh-host/ssh_host_ed25519_key
HostCertificate ${SERVER_DIR}/.ssh-host/ssh_host_ed25519_key-cert.pub
TrustedUserCAKeys ${ca_dir}/ca_user_key.pub
PasswordAuthentication ${SHELL_SSH_PASSWORD_AUTH:-yes}
PubkeyAuthentication yes
PermitRootLogin no
UsePAM no
Subsystem sftp internal-sftp
PrintMotd yes
EOF
    # principals file is OPTIONAL: with the default (none) sshd accepts a cert
    # when its principal == the target username, which our signed certs satisfy.
    # Operators can add /etc/ssh/auth_principals/<user> for stricter mapping.

    log "Starting certificate-sshd on port ${port}..."
    /usr/sbin/sshd -f "${SERVER_DIR}/.ssh-host/sshd_cert_config" -E "${SERVER_DIR}/logs/sshd-cert.log" || {
        fail "sshd (cert profile) failed"
        return 1
    }
    ssh_ready_wait "${port}" && ok "SSH CA-cert server ready on port ${port}"

    chmod 600 "${ca_dir}"/ca_*_key 2>/dev/null || true
    SHELL_DESC_EXTRA["ssh-cert"]="
CONNECT (certificate flow - no passwords, no authorized_keys):
  sign YOUR key:   scp -P ${port} root-user@<host>:.ssh-ca/ca_user_key .  (operator only)
  user side:
    ssh-keygen -t ed25519 -f mykey                 # your personal key
    ssh-keygen -s ca_user_key -I me -n <user> -V +52w mykey.pub
    ssh -i mykey -o CertificateFile=mykey-cert.pub -p ${port} <user>@<host>
COMPONENTS:
  TrustedUserCAKeys    sshd trusts any cert signed by ca_user_key
  principals (-n)      the ONLY usernames the cert may log in as
  HostCertificate      server proves identity - clients pin the host CA:
                       @cert-authority * $(cat "${ca_dir}/ca_host_key.pub" 2>/dev/null | cut -c1-40)...
  files on server      ${ca_dir}/  (CA keys, mode 600, back them up)"
    return 0
}

# ---------------------------------------------------------------- Hardened
init_ssh_hardened() {
    local port="${SHELL_BIND_PORT:-22}"
    local dir="${SERVER_DIR}/.ssh-host"
    mkdir -p "${dir}" "${SERVER_DIR}/.ssh-pub" /run/sshd 2>/dev/null || true

    pkg_install openssh-server openssh-sftp-server || true
    have sshd || { fail "sshd unavailable"; return 1; }
    ensure_os_users

    for kt in ed25519 rsa; do
        kf="${dir}/ssh_host_${kt}_key"
        [ -f "${kf}" ] || ssh-keygen -q -t "${kt}" -N '' -f "${kf}" >/dev/null 2>&1 || true
    done

    cat > "${dir}/sshd_hardened_config" << EOF
Port ${port}
ListenAddress 0.0.0.0
HostKey ${dir}/ssh_host_ed25519_key
HostKey ${dir}/ssh_host_rsa_key
# --- auth: keys only, no passwords, no root -------------------------------- #
PermitRootLogin no
PasswordAuthentication no
KbdInteractiveAuthentication no
PubkeyAuthentication yes
AuthorizedKeysFile ${SERVER_DIR}/.ssh-pub/authorized_keys .ssh/authorized_keys
AuthenticationMethods publickey
MaxAuthTries 2
LoginGraceTime 20
# --- crypto: modern algorithms only ---------------------------------------- #
KexAlgorithms curve25519-sha256,curve25519-sha256@libssh.org,diffie-hellman-group16-sha512
Ciphers chacha20-poly1305@openssh.com,aes256-gcm@openssh.com,aes128-gcm@openssh.com
MACs hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com
# --- session hygiene -------------------------------------------------------- #
ClientAliveInterval 300
ClientAliveCountMax 2
AllowTcpForwarding no
X11Forwarding no
PermitTunnel no
GatewayPorts no
AllowAgentForwarding no
UsePAM no
Subsystem sftp internal-sftp
PrintMotd yes
EOF
    # seed authorized_keys from SHELL_SSH_PUBKEY_RAW if provided
    if [ -n "${SHELL_SSH_PUBKEY_RAW:-}" ]; then
        printf '%s\n' "${SHELL_SSH_PUBKEY_RAW}" > "${SERVER_DIR}/.ssh-pub/authorized_keys"
    fi
    # sshd reads authorized_keys as the TARGET USER; the dir must be traversable
    chmod 755 "${SERVER_DIR}" 2>/dev/null || true
    chmod 755 "${SERVER_DIR}/.ssh-pub" 2>/dev/null || true
    chmod 644 "${SERVER_DIR}/.ssh-pub/authorized_keys" 2>/dev/null || true

    log "Starting hardened sshd on port ${port} (keys-only)..."
    /usr/sbin/sshd -f "${dir}/sshd_hardened_config" -E "${SERVER_DIR}/logs/sshd-hardened.log" || {
        fail "hardened sshd failed"
        return 1
    }
    ssh_ready_wait "${port}" && ok "Hardened SSH ready on port ${port} (keys-only)"
    SHELL_DESC_EXTRA["ssh-hardened"]="
CONNECT (keys only - passwords are rejected by design):
  1) put your PUBLIC key on the server:
       panel file manager -> .ssh-pub/authorized_keys (one key per line)
       or pass SHELL_SSH_PUBKEY_RAW startup variable
  2) connect:
       ssh -p ${port} -i ~/.ssh/id_ed25519 <user>@<host>
  KEY COMPONENTS:
  AuthenticationMethods publickey   password logins impossible, keys mandatory
  chacha20/aes-gcm                  modern AEAD ciphers only
  MaxAuthTries 2                    brute-force budget near zero
  forwarding disabled               pure shell/sftp box - no pivots allowed"
    return 0
}

# ---------------------------------------------------------------- Dropbear
init_dropbear() {
    pkg_install dropbear || true
    have dropbear || { fail "dropbear not available"; return 1; }

    local db_dir="${SERVER_DIR}/.ssh-host"
    mkdir -p "${db_dir}"
    if [ ! -f "${db_dir}/dropbear_rsa_host_key" ]; then
        dropbearkey -t rsa -f "${db_dir}/dropbear_rsa_host_key" >/dev/null 2>&1 || true
    fi
    [ -f "${db_dir}/dropbear_rsa_host_key" ] || { fail "dropbear keygen failed"; return 1; }

    ensure_os_users

    local port
    port=$(allocate_port "dropbear" "${SHELL_BIND_PORT:-22}")
    dropbear -r "${db_dir}/dropbear_rsa_host_key" -p "${port}" -E -F 2>&1 &
    CHILD_PIDS["dropbear"]=$!
    disown 2>/dev/null || true
    ssh_ready_wait "${port}" && ok "Dropbear SSH ready on port ${port}" || warn "Dropbear not answering yet (continuing)"
    SHELL_DESC_EXTRA["dropbear"]="ssh -p ${port} <user>@<host>"
    return 0
}

# ---------------------------------------------------------------- Telnet
init_telnetd() {
    # busybox telnetd first: one syntax everywhere, /bin/login handles our OS users.
    if ! have busybox; then
        pkg_install busybox || true
    fi

    ensure_os_users

    local port
    port=$(allocate_port "telnetd" "${SHELL_BIND_PORT:-23}")

    write_motd_file /etc/issue.net 2>/dev/null || true

    if have busybox && busybox --list 2>/dev/null | grep -qx 'telnetd'; then
        # full busybox (alpine etc.): native multi-port telnetd
        log "Starting busybox telnetd on port ${port}..."
        busybox telnetd -p "${port}" -l /bin/login 2>&1 &
        CHILD_PIDS["telnetd"]=$!
        disown 2>/dev/null || true
    elif [ -x /usr/bin/python3 ] || have python3; then
        # python telnet server: RFC854 IAC negotiation + shadow auth + PTY shell
        log "Starting python telnetd on port ${port}..."
        TELNET_PORT="${port}" python3 "${SCRIPTS_DIR}/telnetd.py" >> "${SERVER_DIR}/logs/telnetd.log" 2>&1 &
        CHILD_PIDS["telnetd"]=$!
        disown 2>/dev/null || true
    else
        fail "no telnetd available (tried busybox, inetutils)"
        return 1
    fi
    ssh_ready_wait "${port}" && ok "Telnet ready on port ${port}" || warn "Telnet not answering yet (continuing)"
    SHELL_DESC_EXTRA["telnetd"]="telnet <host> ${port}  (plaintext - lab use only)"
    return 0
}

# ---------------------------------------------------------------- Mosh
init_mosh_server() {
    init_mosh_impl "$@"
}
init_mosh_impl() {
    pkg_install mosh || true
    have mosh-server || { fail "mosh-server not available"; return 1; }
    ensure_os_users

    local udp_start="${SHELL_MOSH_UDP_START:-60000}"
    local udp_end=$(( udp_start + ${SHELL_MOSH_UDP_COUNT:-10} - 1 ))
    log "Mosh: UDP ${udp_start}-${udp_end} must be opened on the panel for roaming."
    ok "mosh-server installed; users connect with: mosh --port=${udp_start} <user>@<host>"
    SHELL_DESC_EXTRA["mosh-server"]="mosh --port=${udp_start} <user>@<host> (UDP ${udp_start}-${udp_end})"
    return 0
}
